services:
  postgres-db:
    container_name: crud_postgres_db
    image: postgres:18.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: crud_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

